### ISSUE TITLE
AlreadyCalledError when deepstream client reconnects

### ISSUE THREAD

**Issue by jisaacstone** [jacksonofalltrades/pydeepstream#6]
Appears to be pointing at the `_auth_deferred` attribute of `protocol.DeepstreamFactory`

here -> https://github.com/jacksonofalltrades/pydeepstream/blob/master/deepstreampy_twisted/protocol.py#L258

I can reproduce this by creating an rpc that throws an IOError and then calling it.

I don't know if the `INVALID_RPC_CORRELATION_ID` error is related or not

logs:
```
stdout::23:29:29+0000::Connection to/from tcp4:52.8.133.84:443 was lost in a non-clean fashion: Connection lost
stdout::23:29:29+0000::_connectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
stdout::23:29:29+0000::Deepstream connection state set to CLOSED
stdout::23:29:29+0000::WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
stdout::23:29:29+0000::Scheduling retry 1 to connect <twisted.internet.endpoints.SSL4ClientEndpoint object at 0x7f0684a61f90> in 2.24806517877 seconds.
stdout::23:29:29+0000::Stopping factory <deepstreampy_twisted.protocol.WSDeepstreamFactory object at 0x7f067f3b2650>
stdout::23:29:32+0000::Starting factory <deepstreampy_twisted.protocol.WSDeepstreamFactory object at 0x7f067f3b2650>
stdout::23:29:32+0000::Starting DS factory
stdout::23:29:32+0000::connection to tcp4:52.8.133.84:443 established
stdout::23:29:32+0000::GET /deepstream HTTP/1.1
Host: labs.nimblecollective.com:443
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: Y7tbaRqVphg42dHVJjVF8w==
Sec-WebSocket-Version: 13
stdout::23:29:32+0000::Connection made to tcp4:52.8.133.84:443
stdout::23:29:32+0000::connectionMade
stdout::23:29:32+0000::Deepstream connection state set to AWAITING_CONNECTION
stdout::23:29:32+0000::received HTTP response:

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: qW0Pf+ggRd1KWACr0cZ3UBVflhw=
Sec-WebSocket-Version: 13
WebSocket-Server: uWebSockets
stdout::23:29:32+0000::received HTTP status line in opening handshake : HTTP/1.1 101 Switching Protocols
stdout::23:29:32+0000::received HTTP headers in opening handshake : {u'websocket-server': u'uWebSockets', u'connection': u'Upgrade', u'upgrade': u'websocket', u'sec-websocket-version': u'13', u'sec-websocket-accept': u'qW0Pf+ggRd1KWACr0cZ3UBVflhw='}
stdout::23:29:32+0000::openHandshakeTimeoutCall.cancel
stdout::23:29:32+0000::onConnect
stdout::23:29:32+0000::Connected to Server: tcp4:52.8.133.84:443
stdout::23:29:32+0000::Whole response received: {"peer": "tcp4:52.8.133.84:443", "headers": {"websocket-server": "uWebSockets", "connection": "Upgrade", "upgrade": "websocket", "sec-websocket-version": "13", "sec-websocket-accept": "qW0Pf+ggRd1KWACr0cZ3UBVflhw="}, "version": 18, "protocol": null, "extensions": []}
stdout::23:29:32+0000::onOpen
stdout::23:29:32+0000::Connection opened.
stdout::23:29:32+0000::Unhandled Error
Traceback (most recent call last):
  File "/opt/app/scripts/faker", line 136, in fake_launcher
    return nc_launcher.main()
  File "/opt/app/scripts/../nc_appstream/nc_app/nc_launcher.py", line 238, in main
    reactor.run()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 559, in _startRunCallbacks
    raise AlreadyCalledError(extra)
twisted.internet.defer.AlreadyCalledError:
 C: Deferred was created:
 C:  File "/opt/app/scripts/faker", line 186, in <module>
 C:    fake_launcher(args)
 C:  File "/opt/app/scripts/faker", line 136, in fake_launcher
 C:    return nc_launcher.main()
 C:  File "/opt/app/scripts/../nc_appstream/nc_app/nc_launcher.py", line 238, in main
 C:    reactor.run()
 C:  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
 C:    self.mainLoop()
 C:  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
 C:    self.runUntilCurrent()
 C:  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
 C:    call.func(*call.args, **call.kw)
 C:  File "/opt/app/scripts/../nc_appstream/nc_core/deepstream.py", line 35, in login
 C:    client.login(credentials)
 C:  File "/usr/local/lib/python2.7/site-packages/deepstreampy_twisted/interface.py", line 111, in login
 C:    return self._connection.authenticate(auth_params)
 C:  File "/usr/local/lib/python2.7/site-packages/deepstreampy_twisted/interface.py", line 205, in authenticate
 C:    self.factory.authenticate(auth_params)
 C:  File "/usr/local/lib/python2.7/site-packages/deepstreampy_twisted/protocol.py", line 258, in authenticate
 C:    self._auth_deferred = defer.Deferred()
 I: First Invoker was:
 I:  File "/opt/app/scripts/faker", line 186, in <module>
 I:    fake_launcher(args)
 I:  File "/opt/app/scripts/faker", line 136, in fake_launcher
 I:    return nc_launcher.main()
 I:  File "/opt/app/scripts/../nc_appstream/nc_app/nc_launcher.py", line 238, in main
 I:    reactor.run()
 I:  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
 I:    self.mainLoop()
 I:  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
 I:    self.runUntilCurrent()
 I:  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
 I:    call.func(*call.args, **call.kw)
stdout::23:29:32+0000::Received: P|E|INVALID_RPC_CORRELATION_ID|unexpected state for rpc streamsession/41/status with action A+
```

**Comment by AnOctopus** [comment]
@jisaacstone 
I believe I have found the fix for this, but I'm going to need a test case to let me reproduce the issue so I can verify it works, which I'll need before I can close the issue.

**Comment by jisaacstone** [comment]
OK I'll see when I get time. It is nontrivial to do
